name: Compile PDF
run-name: ${{ gitea.actor }} is compiling a PDF 🚀
on: [push]

jobs:
  Compile-PDF:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
      - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: Archive artifacs
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: thesis
          path: thesis.pdf
      - name: Upload to S3
        uses: bxb100/action-upload@main
        with:
          provider: s3
          provider_options: |
            root=/
            region=${{ secrets.S3REGION }}
            bucket=${{ secrets.S3BUCKET }}
            endpoint=${{ secrets.S3ENDPOINT }}
            access_key_id=${{ secrets.S3ACCESSKEY }}
            secret_access_key=${{ secrets.S3ACCESSSECRET }}
          include: '*.pdf'
      - run: echo "🍏 This job's status is ${{ job.status }}."
